name: Check PR

on:
  push:
    branches: [ "main" ]    
  pull_request:
    branches: [ "main" ]
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make init          
                    
      - name: Run Lint
        run: make lint
        
      - name: Send Telegram Message
        run: |
          TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID=${{ secrets.TELEGRAM_CHAT }}
          MESSAGE="New PR opened: ${{ github.event.pull_request.html_url }}"
          
          URL="https://api.telegram.org/bot$TOKEN/sendMessage"
          DATA="chat_id=$CHAT_ID&text=$MESSAGE"
          
          curl -s -X POST "$URL" -d "$DATA"
