version: "3.8"

services:

  db:
    image: elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    volumes:
      - db_data:/usr/share/elasticsearch-one/data
    ports:
      - 9200:9200    

  cache:
    image: redis:7.2.1    
    volumes:
      - cache_data:/data
    ports:
      - 6379:6379

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev        
    volumes:
      - ./app:/app
    depends_on:
      - db
      - cache
    ports:
      - 8000:8000

volumes:
  db_data:
  cache_data:


