version: "3.8"

services:

  db:
    image: elasticsearch:${DB_VERSION}
    environment:
      - discovery.type=single-node
    volumes:
      - db_data:/usr/share/elasticsearch-one/data  
    env_file:
      - ./.env.prod
    expose:
      - ${DB_PORT} 

  cache:
    image: redis:${CACHE_VERSION}  
    volumes:
      - cache_data:/data
    env_file:
      - ./.env.prod
    expose:
      - ${CACHE_PORT}    

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod 
    depends_on:
      - db
      - cache
    env_file:
      - ./.env.prod
    expose:
      - ${APP_PORT}  

  nginx:
    image: nginx:${NGINX_VERSION}  
    depends_on:
      - app
    volumes:
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/default.conf.tmp:/etc/nginx/conf.d/default.conf.tmp
    command: >
      /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
      < /etc/nginx/conf.d/default.conf.tmp
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    env_file:
      - ./.env.prod
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}

volumes:
  db_data:
  cache_data:


