FROM python:3.10-slim
ENV APP_HOME=/app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR $APP_HOME
RUN apt-get update && \
    apt-get install -y gettext && \
    apt install -y ncat && \
    python -m pip install --upgrade pip && \
    pip3 install poetry
COPY . $APP_HOME
RUN poetry config virtualenvs.create false
RUN poetry install
RUN chmod +x ./docker-entrypoint.dev.sh
RUN useradd appuser && chown -R appuser $APP_HOME
USER appuser
EXPOSE 8000
ENTRYPOINT ["./docker-entrypoint.dev.sh"]